### PR TITLE
Fix for userlist

### PR DESCRIPTION
**Pull request by kragebein**
This works for me that doesnt have any local users (FreeIPA/Active Directory setup). Would also work for local users.

### CODE REVIEW

**Review by nwg-piotr — COMMENTED** [review]
I'm don't think it's going to filter out the `ftp` user on Slackware. It does have their home dir.

**Comment by nwg-piotr** [comment]
image

**Comment by kragebein** [comment]
Okay, i've created a check that checks /etc/login.defs to ensure we only get human like users (except root).

Any users that arent a system user should now safely show up. 
But if the userlist is empty, that drop down list should not be a dropdown list, it should be a text field.

**Comment by nwg-piotr** [comment]
> But the application will still fail if the userlist still comes back empty (...)

This should never happen, unless someone creates a new user w/o the `-m` argument. For sure not on nwg-iso, which the greeter was written for. Users created during installation have their home dirs and are visible on the 1st run.

**Pull request merged**
